### ISSUE TITLE
Armory Wishlist

### ISSUE THREAD

**Issue by jonpas** [Theseus-Aegis/Mods#84]
- [x] Replace hints with ACE3 displayTextStructured -> #98
- [x] Add framework for Vanilla gear -> #151
- [x] Use ACE3 events (+ Chronos) -> #109
- [x] Sort lists -> #150
- [x] Add sub-category with magazines/attachments compatible with current weapon -> #178
- [x] Simulate taking and stashing with Vanilla gear -> #202 
- [x] Eden attribute instead of module -> #203 
- [x] ~~Stash All button~~ Default stash to max item quantity -> #410 
- [ ] Eden contents menu for vanilla gear whitelisting
- [ ] Dynamic initializer (load only initialized locker)
- [ ] Locker selection menu
- ~~Icon-less stringtabled buttons (scripted fixed-width text)~~

**Comment by jonpas** [comment]
All currently wanted features and quality of life changes implemented.

- Dynamic initializer and Locker selection menu are a separate big feature that is tracked elsewhere.
- Eden contents menu for vanilla gear whitelisting is not required after ACE Arsenal.
